language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script: npm run build
deploy:
  on: master
  provider: heroku
  app: apparat-generator
  api_key:
    secure: pWD3N9HubNDtVAQP5ggL71xDo3yZHPcV8XAOJrmVPlfm45e5Fy2drPZlUr9bAx3HvoWBV2ycIHdFxmszT1VY7kQ9f8ATw5q3oe08D4wLJhyz09IBoV6usmXsvAQ+MspC3KNNALercBbMbzNI/Si5ik9+eIJBka+ptwsHEDuxSrqWdpUu+2aw/acKQRpNy60SSeUoBAo/sp3e+fdOsqnj8M0grcLRoyxA3h2cDmfghbGHaXwcEGLpMVlDeB13EJKTgJIN6ZezzjvXIpGK5K3JQcl3oJ1gTOUBkHN4sXizTnFJhWDLUR6fplQQ+j/nry/jwLE+J2T2AH8B+hmTL1QRByAqZfJAu7i8wstBJdKMmrqIR9pnPEu7BYoZdAQWMkcpp5krxbvonjWaT3QLhwd0Prw28VbUvp+hsORzfsObm6mHBKA8/Hl2WKTEniN7rwYkbkP/APmMb2HJMmtm8Xemg7fSDiolyfc97gElDXFPbaFYyZaSoNlpHQoHXQn82Dhpfl7ePPvT9inOV1/9+F1phcH6RR+ChTGY1JBK+KPwMS7l5xRmztqkXf1rSkSLVVlAuy8GLAHPBtWHBCns+H4EaUPCKWkdNtoyevC7DA0G8bWqnflaKIl80o7h0szK5hUdYIn9vNPNfogWM4aMMV7WuonnCEH/6zG6zC52Ic1jsLY=
  skip_cleanup: true
